# Generated by Django 3.2.5 on 2025-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20251117_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Space'),
            preserve_default=False,
        ),
    ]
